src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date d'arrivée doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date de fin doit être au bon format")
     * @Assert\GreaterThan(propertyPath="StartDate", message="La date de depart doit être plus eloigner que celle d'arrivé !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amout;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Calcul de la duré
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        
            $this->amout = $this->ad->getPrice() * $this->getDuration();
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    /**
     * Permet de ne pas avoir é reservation sur la même date
     *
     * @return boolean
     */
    public function isBookableDate()
    {
        //REtrouve les dates qui sont imposible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        //compare les dates choisies avec les dates imposibles
        $bookingDay = $this->getDays();

        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };

        //Tableau des chaines de caractères de mes journées
        $days = array_map($formatDay, $bookingDay);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }
        return true;
    }

    /**
     * Permet de recuperer un tableau des journées qui correspond à ma reservation
     * 
     * @return array un Tableau d'objet DateTime représenant les jours de la réservation
     */
    public function getDays()
    {
        $result = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmout(): ?float
    {
        return $this->amout;
    }

    public function setAmout(float $amout): self
    {
        $this->amout = $amout;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transform;

    public function __construct(FrenchToDateTimeTransformer $transform)
    {
        $this->transform = $transform;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfig("Heure de d'arrivé", "Veuillez mettre votre date au quel vous comptez arrivez"))
            ->add('endDate', TextType::class, $this->getConfig("Heure de départ", "Veuillez mettre votre date au quel vous comptez partir"))
            ->add('comment', TextareaType::class, $this->getConfig(false, "Si vous avez un commentaire hesister pas en faire part !", [
                'required' => false
            ]));

        $builder->get('startDate')->addModelTransformer($this->transform);
        $builder->get('endDate')->addModelTransformer($this->transform);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            "validation_groups" => ["Default", "front"]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Ad;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class BookingController extends AbstractController
{

    /**
     * @Route("/ads/{slug}/book", name="booking_route")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request): Response
    {
        $booking =  new Booking();

        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();

            $booking->setBooker($this->getUser())
                ->setAd($ad);
            //CréationDateReservation + CalculMontant : voir Entity booking->prePersist();

            //Verifie si les dates ne sont pas disponible
            if (!$booking->isBookableDate()) {
                $this->addFlash('warning', "Les dates choisi ne peuvent être réserves : elles sont deja occuper");
            } else {
                $em->persist($booking);
                $em->flush();

                return $this->redirectToRoute("booking_show", ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }


        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/booking/{id}", name="booking_show")
     * @Security("is_granted('ROLE_USER') and user === booking.getBooker()", message="Cette reservation ne vous appartient pas !")
     * 
     */
    public function show(Request $request, Booking $booking)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $comment->setAuthor($this->getUser());
            $comment->setAd($booking->getAd());
            $em->persist($comment);
            $em->flush();

            $this->addFlash('success', 'Votre commentaire à bien été pris en compte !');
        }

        return $this->render("booking/show.html.twig", [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reserver l'annonce :
	{{ad.title}}
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous"/>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Réservez pour l'annonce :
			<em>{{ad.title}}</em></h1>

		<p>Vous êtes sur le point de rése'rver le bien de
			<strong>{{ ad.author.fullName }}</strong>, dite nous tout, on s'occupe du reste</p>

		{{form_start(form)}}
		<div class="alert alert-light">
			<h2 class="h4" >Commencez par me dire quellles sont les dates qui vous intéressent !</h2>
			<div class="row input-daterange ">
				<div class="col-6">
					{{form_row(form.startDate)}}
				</div>
				<div class="col-6">
					{{form_row(form.endDate)}}
				</div>
			</div>
		<h4 class="mt-2">Montant du sejour :
			<span id="amout">..</span>
			&euro;
		</h4>
		<span id="days">0</span>
		nuit(s) à
		{{ad.price|number_format(2, ',', ' ') }} &euro;
		par nuit
		<h4 class="mt-3">Vous avez un commentaire ?</h4>
		{{ form_row(form.comment) }}
		</div>

		<h2>Vous avez terminé !</h2>
		<p>Vacances de rêce ? herbegement pour le boulot ? peu, importe, on est avec vous !</p>


		<button class="btn btn-success" type="submit">Reserver</button>
		{{form_end(form)}}
	</div>
{% endblock %}

{% block javascripts %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js" integrity="sha256-JIBDRWRB0n67sjMusTy4xZ9L09V8BINF0nd/UUUOi48=" crossorigin="anonymous"></script>
	<script>
	$.fn.datepicker.defaults.format = 'dd/mm/yyyy';
	$.fn.datepicker.dates['en'] = {
		days:["dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi"],
		daysShort: ["dim.","lun.","mar.","mer.","jeu.","ven.","sam."],
		daysMin:["d","l","ma","me","j","v","s"],
		months:["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"],
		monthsShort:["janv.","févr.","mars","avril","mai","juin","juil.","août","sept.","oct.","nov.","déc."],
		today: "Aujourd'hui",
		clear: "Effacer",
		titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
		weekStart: 0
	};

	$(document).ready(function(){
		$('#booking_startDate, #booking_endDate').datepicker({
			datesDisabled: [
				{% for day in ad.notAvailableDays %}
					"{{day.format('d/m/Y')}}",
				{% endfor %}
			],
			startDate: new Date()
		});

	$('.input-daterange').each(function() {
		$(this).datepicker('clearDates');
	});
	});

	$('#booking_startDate, #booking_endDate').on('change', calculAmout)

	function calculAmout(){
		//Recuperer les dates, et les transform au bon format
		const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
		const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

		if (startDate && endDate && startDate < endDate) {
			const DAY_TIME = 24 * 60 * 60 * 1000;
			const interval = endDate.getTime() - startDate.getTime();
			const days = interval / DAY_TIME;
			const amout = days * {{ ad.price }}

			$('#days').text(days);
			$('#amout').text(amout.toLocaleString('fr-FR'))
		}
	}


	</script>
{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block title %}reservation n°{{booking.id}}
{% endblock %}

{% block body %}
	{% set ad = booking.ad %}
	{% set author = ad.author %}

	<div class="container">

		<h1 class="my-5">Votre réservation (n°{{ booking.id }})</h1>

		{% if app.request.query.get('withAlert') %}
			<div class="alert alert-success">
				<h4 class="alert-heading">
					Bravo
				</h4>
				<p>Votre resarvation auprès de
					<strong>
						<a href="{{ path('user_profil', {'slug' : author.slug}) }}">{{ author.fullName }}</a>
					</strong>
					pour l'annonce
					<strong>
						<a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}</a>
					</strong>
					a bien été prise en compte
				</p>

			</div>
		{% endif %}

		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Details</h2>
					<dl class="row">
						<dt class="col-4">numero</dt>
						<dd class="col-8">{{ booking.id }}</dd>
						<dt class="col-4">Date Arrivé</dt>
						<dd class="col-8">{{ booking.startDate | date('d-m-Y')}}</dd>
						<dt class="col-4">Date de fin
						</dt>
						<dd class="col-8">{{ booking.endDate | date('d-m-Y')}}</dd>
						<dt class="col-4">Total de nuit:</dt>
						<dd class="col-8">{{ booking.duration }}</dd>
						<dt class="col-4">Montant total:</dt>
						<dd class="col-8">{{ booking.amout |number_format(2, ',', ' ') }}&euro;</dd>
						<dt class="col-4">Commentaire</dt>
						<dd class="col-8">{{ booking.comment | default('Aucun commentaire')}}</dd>
					</dl>
					<hr>


					<h2 class="alert-heading">Votre hôte</h2>
					<div class="row mb-3">
						<div class="col-3">
							<img src="{{ author.picture }}" alt="Avater de {{ author.fullName }}" class="avatar avatar-meduim">
						</div>
						<div class="col-9">
							<h4>
								<a href="{{ path('user_profil', {'slug' : author.slug}) }}">{{ author.fullName }}</a>
							</h4>
							<span class="badge badge-primary">{{ author.ads | length }}
								annonces</span>
						</div>
					</div>
					{{author.description | raw}}
					<a href="{{ path('user_profil', {'slug' : author.slug}) }}" class="btn btn-primary">Plus d'info sur
						{{ author.firstName }}</a>
				</div>

				<div class="alert alert-light">
					<h2 class="alerrt-heading">Votre avis compte !</h2>
					{% if date() > date(booking.endDate)  %}
						{% set comment = booking.ad.commentFromAuthor(app.user) %}
						{% if comment is not null %}
							<blockquote>{{comment.content}}</blockquote>

							<strong>Note :
								{% include "partials/rating.html.twig" with {'rating' : comment.rating, 'comment' : booking.ad.comments} %}</strong>
						{% else %}
							{{form_start(form)}}
							{{form_widget(form)}}
							<button class="btn btn-primary" type="submit">Validée</button>
							{{form_end(form)}}
						{% endif %}

					{% else %}
						<p>Vous ne puvez pas, noter cette anonnce tant que votre voyage ne sera pas complet</p>
					{% endif %}
				</div>


			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2 class="alert-heading">Votre hébergement</h2>
					<h4>
						<a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}</a>
					</h4>
					<img src="{{ ad.coverImage }}" alt="image de {{ ad.title }}" class="img-fluid">
					{{ ad.content | raw }}
					<a href="{{ path('ads_show', {'slug' : ad.slug}) }}" class="btn btn-primary">Plus d'info</a>
				</div>
			</div>
		</div>
	</div>

{% endblock %}