src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"title"}, message="Une autre annonce possede ce titre merci de le modifier")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=6, max=255, minMessage="Le titre est trop court il doit faire plus de 10caractére", maxMessage="Le titre est trop long il doit faire moin de 255 caractére")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, max=255, minMessage="L'introduction est trop court il doit faire plus de 20 caractére", maxMessage="L'introduction est trop long il doit faire moin de 255 caractére")
     */
    private $intro;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50, minMessage="La description est trop court il doit faire plus de 50caractére")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true, cascade={"persist"})
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="Ad", orphanRemoval=true)
     */
    private $comments;
    
    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Init le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        $slugify = new Slugify();
        $this->setSlug($slugify->slugify($this->title));
    }

    /**
     * Recupere un tableau des jours qui sont pas disponibles pour cette annonnce
     *
     * @return array Un tableau d'objet DateTime représetant les jours d'occupation
     */
    public function getNotAvailableDays()
    {
        $notAvaibleDays = [];

        foreach ($this->bookings as $booking) {
            //Calcul les jour qui se trouvent entre la date d'arrivée et la date de depart
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $result);

            $notAvaibleDays = array_merge($notAvaibleDays, $days);
        }

        return $notAvaibleDays;
    }

    /**
     * Permet de obtenier lamioyenne global des notes
     *
     * @return float
     */
    public function getAvgRatings()
    {
        //Calcul des notes totals
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        //Calcul pour la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 'Non noter';
    }

    /**
     * Permet de récupérer le commentaire d'un autre par rapport à un annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
		{{ encore_entry_link_tags('js/app') }}
		<title>
			{% block title %}
				Welcome!
			{% endblock %}
		</title>
		{% block stylesheets %}{% endblock %}
	</head>
	<body>
		{% include 'partials/header.html.twig' %}

		{% block body %}{% endblock %}

		{% include 'partials/footer.html.twig' %}

		{{ encore_entry_script_tags('js/app') }}

		{% block javascripts %}{% endblock %}
	</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}
	AirBnb à la wish
{% endblock %}

{% block body %}
	<div class="container pt-3">

		<div class="jumbotron">
			<h1 class="display-3 glitch-effect">Bienvenue</h1>
			<p class="lead">Nous mettons en relations les voyageur et les propriétaires qui veulent profiter d'opportunitéet gagner de l'argent en proposant leur bien à la location !</p>
			<hr class="my-4">
			<p>Vous  voyageur vous voulait voir on vous pourrez loger, pour votre prochaine deplacement ?</p>
			<p class="lead">
				<a class="btn btn-primary btn-lg" href="{{ path('ads_index') }}" role="button">Voir nos annonces</a>
			</p>
		</div>

		<h2 class="h1 my-5">No top appartement</h2>
		<div class="row">
			{% for topAd in ads %}
				{% set ad = topAd.annonce %}
				<div class="col-4">
					<div class="card bg-light mb-3">
						<div class="card-header text-center">
							{{ad.rooms}}
							chambres,
							<strong>{{ad.price}}
								&euro; /nuit</strong><br>
							<small>{% include "partials/rating.html.twig" with {'rating' : topAd.avgRatings, 'comment' : ad.comments} %}</small>
						</div>

						<img src="{{ad.coverImage}}" alt="Annonce de {{ad.author.fullName}}" style="height: 200px; witdh: 100%; display: block">

						<div class="card-body">
							<h3 class="card-title">
								{{ad.title}}</h3>
							<p class="card-text">
								{{ad.intro}}
							</p>
							<a href="{{ path('ads_show', {'slug' : ad.slug}) }}" class="btn btn-success">En savoir plus</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>


	<h2 class="h1 my-5">Les stars !</h2>

	<div class="row">
		{% for topUser in users %}
			{% set user = topUser.user %}
			<div class="col">
				<div class="card border-secondary mb-3">
					<div class="card-body">
						<h4 class="card-title">{{user.fullName}}</h4>
						<hr>
						<div class="card-text">
							<img src="{{user.picture}}" alt="Le best" class="float-left mr-3 avatar">
							<p>{{user.intro}}</p>
							<a href="{{ path('user_profil', {'slug' : user.slug}) }}" class="btn btn-success float-right">En savoir +</a>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>{% endblock %}